export {default as BodyWrapper } from './Wrapper/BodyWrapper'
export {default as ContentWrapper } from './Wrapper/ContentWrapper'
export {default as ContentBody } from './Wrapper/ContentBody'
export {default as Block } from './Wrapper/Block'
export {default as HeadWrapper } from './Wrapper/HeadWrapper'

export { default as Login }  from './Login/Login'
export { default as Register }  from './Register/Register'
export { default as Dashboard }  from './Dashboard/Dashboard'
export { default as MyForms }  from './MyForms/MyForms'
export { default as PaymentHistory }  from './PaymentHistory/PaymentHistory'
export { default as MySubscription }  from './MySubscription/MySubscription'
export { default as ManageTeam }  from './ManageTeam/ManageTeam'
export { default as Download }  from './Download/Download'
export { default as Pricing }  from './Pricing/Pricing'
export { default as SubscriptionDetail }  from './SubscriptionDetail/SubscriptionDetail'
export { default as Invoices }  from './Invoices/Invoices'
export { default as Tickets }  from './Tickets/Tickets'
export { default as TicketDetail }  from './TicketDetail/TicketDetail'
export { default as CreateForm }  from './CreateForm/CreateForm'

export { default as MyProfile }  from './MyProfile/MyProfile'
export { default as Personal }  from './MyProfile/Personal'
export { default as Settings }  from './MyProfile/Settings'
export { default as Notification }  from './MyProfile/Notification'
export { default as Billing }  from './MyProfile/Billing'


